### ISSUE TITLE
Tree Executor

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibocal#233]
Here the basic layout (as pseudo-Python-code, don't take too seriously), for a tree runcard executor.
Sequential, single-threaded, but we might scale later on (but we won't if it is not needed).

The new runcard is going to be very similar to the current one, and it will resemble the following:
```yaml
global-par1: ...
global-par2: ...
global-par3: ...

actions:
  - id: resonator_punchout-1
    action: resonator_spectroscopy
    par1: ...
    par2: ...
  - id: resonator_spectroscopy-1
    action: resonator_spectroscopy
    par1: ...
    par2: ...
    requires: [resonator_punchout-1]
  ...
```
(all the `*par*` are of course placeholders)

The key properties are the `id` and `requires`, which define the tree itself.

Then:
```py
# --- operation.py ---
import resonator_spectroscopy, resonator_punchout

class Operation(enum.Enum):
    """available operations"""
    resonator_spectroscopy = resonator_spectroscopy
    resonator_punchout = resonator_punchout

# --- task.py ---

Id = str

class TaskParameter(Generic[T]):
    value: Optional[T]
    source: Optional[Id]

@abstract
class Parameters:
    pass

@abstract
class Update
    pass

@abstract
class Output
    status: Status
    results: Results
    update: Update

class Task:
    operation: Operation
    parameters: Parameters
    requirements: dict[Id, bool]

    @classmethod
    def load(cls, card):
         name = ...
         parameters = ...
         requirements = ...
         return cls(operation=Operation[name], parameters=parameters, requirements=requirements) 

    def run(self) -> Output:
        self.operation.value(self.parameters)

# --- pending.py ---

class Queue:
    queue: list[Task]

    def free(self, completed=None):
        ready = []
        for task in queue:
            task.complete(completed)
            if task.ready:
                 queue.drop(task)
                 ready.append(task)
             
        return ready

# --- history.py ---

class Completed:
    task: Task
    output: task.Output

class History:
    steps: list[Completed]

    def record(self, task: Task, output: task.Output):
        completed = Completed(task, output)
        self.steps.push(completed)

    def time_travel(self, initial: Platform, time: int):
        plat = initial.copy()
        for step in steps[:time]:
            plat.update(step.output.update)

        return plat

# --- execute.py ---

class ExecutionQueue:
    queue: list[Task]

    def __iter__(self):
        wip = self.queue.pop(0)
        yield wip, wip.run()

class Executor:
    exec_queue: ExecutionQueue
    pending_queue: pending.Queue
    history: History
    outputs: dict[TaskId, TaskOutput]

    @classmethod
    def load(cls, card):
        pendings = [Task.load(action) for action in card.actions]
        return cls(exec_queue=[], pending_queue=pendings, outputs={})

    def run(self):
         self.exec_queue.extend(self.pending.free())
         for wip_task in self.exec_queue:
             self.history.record(wip)
             self.exec_queue.extend(self.pending.free(completed=wip_task.id))

         if len(self.pending_queue) > 0:
              raise RuntimeError("Execution completed but tasks still pending")
```

- [ ] execute calibration steps
- [ ] modify platform status
- [ ] define steps input
- [ ] time-travelling platform
    - reconstruct platform at time T from diffs saved in `History`
- [ ] negotiate platform update with `qibolab` @stavros11 
    - the update should be done by the platform object in `qibolab`, given an `Update` object, that should be defined in `qibolab` itself 
    - we can also have a `qibocal` version of `Update`, to reduce the interface, and just implement the conversion from `qibocal.task.Update -> qibolab.platform.Update` (this is the only arrow needed)

**Comment by AleCandido** [comment]
@Edoardo-Pedicillo when you will start implementing this, start from the test: make a test runcard (not necessarily YAML, just a Python list of placeholder "tasks") and we will start from there.

It is a rather simple design, but if you can't run it until the very end you will increase a lot the chances of introducing bugs.
