### ISSUE TITLE
Gate-set characterization roadmap

### ISSUE THREAD

**Issue by vodovozovaliza** [qiboteam/qibocal#411]
- [ ] Z2 filtered RB ($Z_2=\\{I,X\\}$)
- [ ] Clifford simultaneous (correlated) filtered RB
- [ ] Filtered RB for other small groups (e.g. Heisenberg-Weyl, $Z_k=\\{R_x(j\cdot 2\pi/k)\\}_{j=0}^{k-1}$)
- [ ] two-qubit Clifford
- [ ] cycle benchmarking
- [ ] Pauli noise learning
- [ ] gate-set shadows for robust QPT
- [ ] GST integration
- [ ] Overlapping detector tomography

https://github.com/qiboteam/qibocal/pull/349#issuecomment-1577998975
