### ISSUE TITLE
Towards autocalibration

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/qibocal#498]
This issue summarizes all the next steps required to reach a minimal autocalibration prototype.
In brackets, I tried to estimate their completion times.
Please take this evaluation as purely indicative to design a timeline. 
I remember that #336 and @aorgazf 's issues report
other useful features that can improve the quality of the autocalibration project.

## Missing Routines

- [ ]  `Chevron` fitting (1 week). #490
- [ ]  Parameters update in `Tune Landscape` (1 week). #491
- [ ]  Amplitude Readout Optimization (2 weeks). #492
- [ ]  TWPA characterization routine (2 weeks). #478
- [ ]  Avoided Crossing (2 weeks). #493
- [ ]  SNZ (2 weeks). #494
- [ ]  Leakage Optimization (2 weeks). #495
- [ ]  Concluding Cryoscope routine (2 weeks). #460
- [ ] Error bars propagation (2 weeks). #450
- [ ] CHSH (1 week). #452
- [ ] Readout Mitigation Matrix (1 week). #452
- [ ] Flux Crosstalk matrix (1 week). #462

## Missing Cyclic Graph Features

- [ ] Single Node Optimizer (2 weeks). #496
- [ ] Exceptional Flow (1 month). #497

## General Maintenance and Improvements

- [ ] Operational modes (1 week). #406
- [ ] Documentation (2 weeks). #485

**Comment by andrea-pasquale** [comment]
Closing this since at the moment the DAG is not supported anymore.
